apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 1-replicas
  name: 1-replicas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1-replicas
  template:
    metadata:
      labels:
        app: 1-replicas
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.2-alpine-slim
