apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: 1-replicas
  name: 1-replicas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1-replicas
  template:
    metadata:
      labels:
        app: 1-replicas
    spec:
      containers:
      - image: nginx
        name: nginx:nginx:1.27.2-alpine-slim
