# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #=============#
  # Master Node #
  #=============#

  (11..13).each do |i|
    config.vm.define "m#{i}-k8s" do |cfg|
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "m#{i}-k8s(github_SysNet4Admin)"
        vb.cpus = 2
        #vb.memory = 1536
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/k8s-MtpMST-kubespray(github_SysNet4Admin)"]
      end
      cfg.vm.host_name = "m#{i}-k8s"
      cfg.vm.network "public_network", ip: "192.168.1.#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "600#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "file", source: "auto_pass.sh", destination: "auto_pass.sh"
      cfg.vm.provision "shell", path: "install_pkg.sh"
      cfg.vm.provision "shell", path: "config.sh"
      if i == 11
        cfg.vm.provision "shell", path: "pre-kubespray.sh"
      end
    end 
  end

  #==============#
  # Worker Nodes #
  #==============#

  (101..106).each do |i|
    config.vm.define "w#{i}-k8s" do |cfg|  
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}-k8s(github_SysNet4Admin)"
        vb.cpus = 1
        #vb.memory = 1280 
        vb.memory = 1536 
        vb.customize ["modifyvm", :id, "--groups", "/k8s-MtpMST-kubespray(github_SysNet4Admin)"]
      end
      cfg.vm.host_name = "w#{i}-k8s"
      cfg.vm.network "public_network", ip: "192.168.1.#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "60#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "file", source: "auto_pass.sh", destination: "auto_pass.sh"
      cfg.vm.provision "shell", path: "install_pkg.sh"
      cfg.vm.provision "shell", path: "config.sh"
    end
  end

end