apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RegoConstraintTemplateNoHostPath
metadata:
  name: rego-constraintnohostpath 
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["DaemonSet", "Pod", "Deployment"]
