apiVersion: apps/v1
kind: Deployment
metadata:
  name: use-pvc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: use-pvc
  template:
    metadata:
      labels:
        app: use-pvc
    spec:
      containers:
      - name: echo-nginx
        image: sysnet4admin/echo-nginx
        volumeMounts:
        - name: pvc-vol # same name of volumes's name 
          mountPath: /pvc-vol
      volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: claim-pvc # same name of pvc that was created