# -*- mode: ruby -*-
# vi: set ft=ruby :

# each of components to install 
k8s_V = '1.29.2-1.1'           # Kubernetes
docker_V = '5:24.0.6-1~ubuntu.22.04~jammy' # Docker  
ctrd_V = '1.6.21-1'   # Containerd 
## /configuration variables ##

Vagrant.configure("2") do |config|
  config.vm.define "rubra-ai" do |cfg|
    cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "rubra-ai"
      vb.cpus = 4
      vb.memory = 16384
      vb.customize ["modifyvm", :id, "--groups", "/AIOps(github_SysNet4Admin)"]
    end
    cfg.vm.host_name = "rubra-ai"
    cfg.vm.network "private_network", ip: "192.168.1.231"
    cfg.vm.network "forwarded_port", guest: 22, host: 60231, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    cfg.vm.provision "shell", path: "env_build.sh", args: k8s_V[0..3]
    cfg.vm.provision "shell", path: "docker_build.sh", args: docker_V 
    cfg.vm.provision "shell", path: "minikube-build.sh", args: k8s_V
    cfg.vm.provision "shell", path: "custom-git.sh" # custom-by-user whatever you want 
  end
end
