apiVersion: authentication.gke.io/v2alpha1
kind: ClientConfig
metadata:
  name: default
  namespace: kube-public
spec:
  authentication:
  - name: oidc
    oidc:
      clientSecret: Sw37vsOW7GdPQMAbjPqfR1q3bhD7sdLa
      clientID: k8s-auth 
      cloudConsoleRedirectURI: https://console.cloud.google.com/kubernetes/oidc
      extraParams: resource=token-groups-claim
      groupPrefix: '-'
      groupsClaim: groups
      issuerURI: https://oncloud-2.site/realms/kubernetes
      kubectlRedirectURI: http://localhost:8000
      scopes: openid
      userClaim: preferred_username
      userPrefix: '-'
  internalServer: ""
  name: hj-keycloak
  # server: manually input after applying clientconfig or searching and add 
status: {}
