apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-chk-info
  labels:
    app: deploy-chk-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-chk-info
  template:
    metadata:
      labels:
        app: deploy-chk-info 
    spec:
      containers:
      - name: chk-info
        image: sysnet4admin/chk-info
---
apiVersion: v1
kind: Service
metadata:
  name: lb-chk-info 
spec:
  selector:
    app: deploy-chk-info  
  ports:
    - name: http
      port: 80
      targetPort: 80 
  type: LoadBalancer

