apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: sysnet4admin
        image: sysnet4admin/echo-nginx
        ports:
        - containerPort: 80