apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: no-matched-replicass
  name: no-matched-replicas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: no-matched-replicas
  template:
    metadata:
      labels:
        app: no-matched-replicas
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.2-alpine-slim
        volumeMounts:
        - mountPath: /host-log
          name: hostpath-directory
      volumes:
      - name: hostpath-directory
        hostPath:
          path: /var/log
