 # Source: prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-prometheus-node-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: gke-prometheus-node-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: gke-prometheus-node-exporter
  name: gke-prometheus-node-exporter
  namespace: default 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gke-prometheus-node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gke-prometheus-node-exporter
    spec:
      containers:
      - args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        image: quay.io/prometheus/node-exporter:v1.1.2
        #image: prom/node-exporter:v0.18.1
        imagePullPolicy: IfNotPresent
        name: gke-prometheus-node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      serviceAccount: gke-prometheus-node-exporter
      serviceAccountName: gke-prometheus-node-exporter
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
  updateStrategy:
    type: OnDelete
---
# Source: prometheus-node-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gke-prometheus-node-exporter
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: gke-prometheus-node-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: gke-prometheus-node-exporter

