apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hj-keycloak-demo-aws
  region: us-east-2

nodeGroups:
  - name: compute-group
    instanceType: t3a.small
    desiredCapacity: 3

identityProviders:
  - name: keycloak
    type: oidc
    issuerUrl: https://oncloud-2.site/realms/kubernetes
    clientId: k8s-auth 
    usernameClaim: preferred_username
    usernamePrefix: 
    groupsClaim: groups
