apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-svr-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-svr-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi