apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nfs-deploy
  template:
    metadata:
      labels:
        app: nfs-deploy
    spec:
      serviceAccountName: nfs-provisioner
      containers:
      - name: audit-trail
        image: sysnet4admin/audit-trail
        volumeMounts:
        - name: nfs-vol
          mountPath: /audit
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-sc