---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: use-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: use-pvc
  serviceName: use-pvc
  template:
    metadata:
      labels:
        app: use-pvc
    spec:
      containers:
      - name: echo-nginx
        image: sysnet4admin/echo-nginx
        volumeMounts:
        - name: vct-vol # same name of volumes's name
          mountPath: /pvc-vol
  volumeClaimTemplates:
  - metadata:
      name: vct-vol
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-svr-sc"
      resources:
        requests:
          storage: 1Gi
