# -*- mode: ruby -*-
# vi: set ft=ruby :

# each of components to install 
k8s_V = '1.23.14-00'           # Kubernetes
docker_V = '5:20.10.21~3-0~ubuntu-jammy' # Docker  
#ctrd_V = '1.4.4-3.1.el7'   # Containerd 
minikube_V = 'v1.25.2'
## /configuration variables ##

Vagrant.configure("2") do |config|
  config.vm.define "demo-prom-darksite" do |cfg|
    cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "demo-prom-darksite"
      vb.cpus = 2
      vb.memory = 2048 # the required 1800MiB for Kubernetes
      vb.customize ["modifyvm", :id, "--groups", "/k8s-dev-tools(github_SysNet4Admin)"]
    end
    cfg.vm.host_name = "demo-prom-darksite"
    cfg.vm.network "private_network", ip: "192.168.1.248"
    cfg.vm.network "forwarded_port", guest: 22, host: 60248, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    cfg.vm.provision "shell", path: "minikube-build.sh", args: [ k8s_V, docker_V, minikube_V ]
    cfg.vm.provision "shell", path: "prom.sh", env: { "PATH" => "$PATH:/usr/local/bin" }
  end
end
