apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hj-keycloak-oncloud-1-eks
  region: us-east-2
  version: "1.27" 

nodeGroups:
  - name: compute-group
    instanceType: t3a.small
    desiredCapacity: 3

identityProviders:
  - name: keycloak
    type: oidc
    issuerUrl: https://oncloud-1.site/realms/kubernetes
    clientId: k8s-auth 
    usernameClaim: preferred_username
    usernamePrefix: 
    groupsClaim: groups
