# -*- mode: ruby -*-
# vi: set ft=ruby :

# each of components to install 
k8s_V = '1.21.1'           # Kubernetes
docker_V = '20.10.6-3.el7' # Docker  
ctrd_V = '1.4.4-3.1.el7'   # Containerd 
## /configuration variables ##

Vagrant.configure("2") do |config|
  config.vm.define "docker-builder" do |cfg|
    cfg.vm.box = "sysnet4admin/CentOS-k8s"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "docker-builder"
      vb.cpus = 2
      vb.memory = 2048
      vb.customize ["modifyvm", :id, "--groups", "/k8s-dev-tools(github_SysNet4Admin)"]
    end
    cfg.vm.host_name = "docker-builder"
    cfg.vm.network "private_network", ip: "192.168.1.91"
    cfg.vm.network "forwarded_port", guest: 22, host: 60091, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    cfg.vm.provision "shell", path: "env_build.sh"
    cfg.vm.provision "shell", path: "docker_build.sh", args: [ docker_V, ctrd_V ]
    cfg.vm.provision "shell", path: "minikube-build.sh", args: k8s_V
    cfg.vm.provision "shell", path: "custom-git.sh" # custom-by-user whatever you want 
  end
end
